import type { Firewall, PolicyInventoryItem, PolicyPayload, Topology } from "./client";

const switches = [
  "access_floor1",
  "access_floor2",
  "core_hq",
  "dist_branch",
  "access_branch",
  "infra_access",
];
const ceNodes = ["ce_hq1", "ce_hq2", "ce_branch1", "ce_branch2"];

export const mockTopology: Topology = {
  nodes: [
    { id: "c0", label: "OS-Ken SDN Controller", type: "controller" },
    { id: "project_1", label: "Dự án 1", type: "user_group", vlan: 101, count: 20, subnet: "10.10.101.0/24" },
    { id: "project_2", label: "Dự án 2", type: "user_group", vlan: 93, count: 20, subnet: "10.10.93.0/24" },
    { id: "project_3", label: "Dự án 3", type: "user_group", vlan: 103, count: 20, subnet: "10.10.103.0/24" },
    { id: "project_4", label: "Dự án 4", type: "user_group", vlan: 104, count: 20, subnet: "10.10.104.0/24" },
    { id: "it_support", label: "Office / IT Support", type: "user_group", vlan: 110, count: 10, subnet: "10.10.110.0/24" },
    { id: "guest", label: "Guest HQ", type: "user_group", vlan: 120, count: 2, subnet: "10.10.120.0/24" },
    { id: "iot_hq", label: "HQ IoT", type: "user_group", vlan: 140, count: 5, subnet: "10.10.140.0/24" },
    { id: "iot_branch", label: "Branch IoT", type: "user_group", vlan: 50, count: 2, subnet: "10.20.50.0/24" },
    { id: "fw_hq", label: "Firewall HQ HA", type: "firewall" },
    { id: "fw_telesale", label: "Firewall Branch HA", type: "firewall" },
    { id: "l2vpn_primary", label: "MPLS L2VPN Primary", type: "l2vpn" },
    { id: "l2vpn_backup", label: "MPLS L2VPN Backup", type: "l2vpn" },
    { id: "ipsec_l3", label: "IPsec L3 Tunnel", type: "ipsec" },
    { id: "h90", label: "PBX / Contact Center", type: "service", ip: "10.250.10.10" },
    { id: "hcall", label: "Partner CRM", type: "service", ip: "10.250.10.20" },
    { id: "internet_zone", label: "Internet / Partner Service Zone", type: "service_edge" },
    { id: "hdhcp", label: "DHCP Server", type: "infrastructure_service", vlan: 100, ip: "10.10.100.10" },
    ...switches.map((id) => ({ id, label: id, type: "switch" })),
    ...ceNodes.map((id) => ({ id, label: id, type: "ce_bridge", controller_managed: false })),
  ],
  groups: [
    {
      id: "project_1",
      label: "Dự án 1",
      type: "user_group",
      site: "hq",
      vlan: 101,
      count: 20,
      subnet: "10.10.101.0/24",
      switch: "access_floor1",
      hosts: [{ name: "h101_01", label: "User 101-01", ip: "10.10.101.11", kind: "user", group: "project_1", group_label: "Dự án 1", vlan: 101, site: "hq" }],
    },
    {
      id: "project_2",
      label: "Dự án 2",
      type: "user_group",
      site: "hq",
      sites: ["hq", "branch"],
      vlan: 93,
      count: 20,
      subnet: "10.10.93.0/24",
      switch: "access_floor1",
      hosts: [
        { name: "h93_01", label: "User 93 HQ", ip: "10.10.93.11", kind: "user", group: "project_2", group_label: "Dự án 2", vlan: 93, site: "hq" },
        { name: "h93_02", label: "User 93 Branch", ip: "10.10.93.12", kind: "user", group: "project_2", group_label: "Dự án 2", vlan: 93, site: "branch" },
      ],
    },
  ],
  hosts: [
    { name: "h101_01", label: "User 101-01", ip: "10.10.101.11", kind: "user", group: "project_1", group_label: "Dự án 1", vlan: 101, site: "hq" },
    { name: "h93_01", label: "User 93 HQ", ip: "10.10.93.11", kind: "user", group: "project_2", group_label: "Dự án 2", vlan: 93, site: "hq" },
    { name: "h93_02", label: "User 93 Branch", ip: "10.10.93.12", kind: "user", group: "project_2", group_label: "Dự án 2", vlan: 93, site: "branch" },
    { name: "h90", label: "PBX / Contact Center", ip: "10.250.10.10", kind: "service", group: "partner", group_label: "Partner", vlan: null, site: "internet" },
    { name: "hcall", label: "Partner CRM", ip: "10.250.10.20", kind: "service", group: "partner", group_label: "Partner", vlan: null, site: "internet" },
  ],
  links: [
    { id: "project_1-access_floor1", source: "project_1", target: "access_floor1", type: "access", status: "up" },
    { id: "access_floor1-core_hq", source: "access_floor1", target: "core_hq", type: "trunk", status: "up" },
    { id: "core_hq-ce_hq1", source: "core_hq", target: "ce_hq1", type: "l2_handoff", status: "up" },
    { id: "ce_hq1-l2vpn_primary", source: "ce_hq1", target: "l2vpn_primary", type: "l2vpn", status: "up" },
    { id: "l2vpn_primary-ce_branch1", source: "l2vpn_primary", target: "ce_branch1", type: "l2vpn", status: "up" },
    { id: "ce_branch1-dist_branch", source: "ce_branch1", target: "dist_branch", type: "l2_handoff", status: "up" },
    { id: "core_hq-ce_hq2", source: "core_hq", target: "ce_hq2", type: "l2_handoff", status: "up" },
    { id: "ce_hq2-l2vpn_backup", source: "ce_hq2", target: "l2vpn_backup", type: "l2vpn", status: "up" },
    { id: "l2vpn_backup-ce_branch2", source: "l2vpn_backup", target: "ce_branch2", type: "l2vpn", status: "up" },
    { id: "ce_branch2-dist_branch", source: "ce_branch2", target: "dist_branch", type: "l2_handoff", status: "up" },
    { id: "dist_branch-access_branch", source: "dist_branch", target: "access_branch", type: "trunk", status: "up" },
    { id: "access_branch-project_2", source: "access_branch", target: "project_2", type: "access", status: "up" },
    { id: "core_hq-fw_hq", source: "core_hq", target: "fw_hq", type: "routed", status: "up" },
    { id: "fw_hq-ipsec_l3", source: "fw_hq", target: "ipsec_l3", type: "ipsec", status: "up" },
    { id: "ipsec_l3-fw_telesale", source: "ipsec_l3", target: "fw_telesale", type: "ipsec", status: "up" },
  ],
  policy_map: {},
  summary: { user_count: 90, service_count: 5, controlled_ovs_count: 6, live_link_control: true },
};

export const mockFirewalls: Firewall[] = [
  {
    name: "Firewall HQ HA Cluster (fw_hq)",
    logical_name: "fw_hq",
    site: "HQ (Trụ sở chính)",
    runtime_status: "verified",
    inside_interface: "eth1 (10.10.10.1/24)",
    outside_interface: "eth0 (203.0.113.1)",
    ipv4_forwarding: true,
    nftables_table: "inet cch_filter",
    chain: "forward",
    rule_count: 36,
    nat: { configured: true, status: "active", conclusion: "MASQUERADE SNAT enabled on eth0 outside" },
    counters: {
      social_deny: { packets: 1420, bytes: 119280 },
      call_allow: { packets: 89450, bytes: 17890000 },
      zalo_allow: { packets: 34120, bytes: 4256000 },
      inbound_deny: { packets: 8540, bytes: 683200 },
    },
  },
  {
    name: "Firewall Branch HA Cluster (fw_telesale)",
    logical_name: "fw_telesale",
    site: "Branch (Chi nhánh)",
    runtime_status: "verified",
    inside_interface: "eth1 (10.20.10.1/24)",
    outside_interface: "eth0 (198.51.100.1)",
    ipv4_forwarding: true,
    nftables_table: "inet cch_filter",
    chain: "forward",
    rule_count: 28,
    nat: { configured: true, status: "active", conclusion: "MASQUERADE SNAT enabled on eth0 outside" },
    counters: {
      social_deny: { packets: 980, bytes: 82320 },
      call_allow: { packets: 65400, bytes: 13080000 },
      zalo_allow: { packets: 21300, bytes: 2662500 },
      inbound_deny: { packets: 5120, bytes: 409600 },
    },
  },
];

export const mockPolicyInventory: PolicyInventoryItem[] = [
  {
    key: "isolate_hq_projects",
    name: "Cô lập các dự án HQ (default-deny L2/L3)",
    description: "Các phân đoạn Dự án 1, 2, 3, 4 tại HQ hoàn toàn cách ly nhau, ngăn chặn lây nhiễm ngang.",
    source: "VLAN 101 / 93 / 103 / 104",
    destination: "VLAN dự án khác",
    action: "DROP",
    enforcement_point: "access_floor1 / access_floor2",
    enforcement_engine: "openflow",
    priority: 400,
    cookie: "0x1001",
    enabled: true,
    configuration_status: "Enabled",
    lifecycle_status: "Applied",
    runtime_acknowledged: true,
    controller_acknowledged: true,
    updated_at: new Date().toISOString(),
  },
  {
    key: "allow_voice",
    name: "Cho phép luồng thoại VoIP (PBX / SBC)",
    description: "Cung cấp kết nối SIP/RTP từ softphone của agent tới Tổng đài PBX/Contact Center h90.",
    source: "VLAN 101 / 93 / 103 / 104 / 110",
    destination: "h90 (PBX 10.250.10.10)",
    action: "ALLOW",
    enforcement_point: "Source enforcement switch",
    enforcement_engine: "openflow",
    priority: 425,
    cookie: "0x1200",
    enabled: true,
    configuration_status: "Enabled",
    lifecycle_status: "Applied",
    runtime_acknowledged: true,
    controller_acknowledged: true,
    updated_at: new Date().toISOString(),
  },
  {
    key: "voice_flow_priority",
    name: "Ưu tiên OpenFlow cho luồng Voice",
    description: "Tăng OpenFlow priority của luồng Voice lên 425; không tuyên bố DSCP hoặc hàng đợi QoS production.",
    source: "any (Voice SIP/RTP)",
    destination: "h90 (PBX)",
    action: "ALLOW",
    enforcement_point: "Source enforcement switch",
    enforcement_engine: "openflow",
    priority: 425,
    cookie: "0x1200",
    enabled: true,
    configuration_status: "Enabled",
    lifecycle_status: "Applied",
    runtime_acknowledged: true,
    controller_acknowledged: true,
    updated_at: new Date().toISOString(),
  },
  {
    key: "vlan93_l2vpn_primary_active",
    name: "MPLS L2VPN E-Line Stretch (VLAN 93 Primary)",
    description: "Mở rộng L2 trong suốt cho Dự án 2 giữa HQ và Chi nhánh qua kênh truyền chính MPLS L2VPN.",
    source: "project_2 (HQ VLAN 93)",
    destination: "project_2 (Branch VLAN 93)",
    action: "ALLOW",
    enforcement_point: "ce_hq1, l2vpn_primary, ce_branch1",
    enforcement_engine: "openflow",
    priority: 35000,
    cookie: "0x3001",
    enabled: true,
    configuration_status: "Enabled",
    lifecycle_status: "Applied",
    runtime_acknowledged: true,
    controller_acknowledged: true,
    updated_at: new Date().toISOString(),
  },
  {
    key: "vlan93_l2vpn_backup_standby",
    name: "MPLS L2VPN Standby Failover Protection",
    description: "Đường truyền dự phòng L2VPN Backup (ce_hq2 - ce_branch2) tự động kích hoạt khi Primary gặp sự cố.",
    source: "ce_hq2",
    destination: "ce_branch2",
    action: "ALLOW",
    enforcement_point: "ce_hq2, l2vpn_backup, ce_branch2",
    enforcement_engine: "openflow",
    priority: 34000,
    cookie: "0x3002",
    enabled: true,
    configuration_status: "Enabled",
    lifecycle_status: "Applied",
    runtime_acknowledged: true,
    controller_acknowledged: true,
    updated_at: new Date().toISOString(),
  },
  {
    key: "intersite_via_ipsec_l3",
    name: "Liên chi nhánh định tuyến qua IPsec L3 Tunnel",
    description: "Lưu lượng L3 giữa các phòng ban khác đi qua đường hầm bảo mật Firewall HA đối bên.",
    source: "HQ Internal Subnets",
    destination: "Branch Subnets",
    action: "ALLOW",
    enforcement_point: "fw_hq, fw_telesale",
    enforcement_engine: "nftables",
    priority: 25000,
    cookie: "0x4001",
    enabled: true,
    configuration_status: "Enabled",
    lifecycle_status: "Applied",
    runtime_acknowledged: true,
    controller_acknowledged: true,
    updated_at: new Date().toISOString(),
  },
  {
    key: "allow_call_app",
    name: "Cho phép kết nối Partner CRM & Telesale",
    description: "Đảm bảo truy cập các hệ thống nghiệp vụ CRM và quản lý cuộc gọi đối tác tại hcall.",
    source: "project_1..4",
    destination: "hcall (Partner CRM 10.250.10.20)",
    action: "ALLOW",
    enforcement_point: "fw_hq / fw_telesale",
    enforcement_engine: "nftables",
    priority: 0,
    cookie: "n/a",
    enabled: true,
    configuration_status: "Enabled",
    lifecycle_status: "Applied",
    runtime_acknowledged: true,
    controller_acknowledged: true,
    updated_at: new Date().toISOString(),
  },
  {
    key: "allow_zalo",
    name: "Cho phép ứng dụng Zalo Doanh nghiệp",
    description: "Cho phép lưu lượng trao đổi công việc qua Zalo API/Chat gateway.",
    source: "Managed Users",
    destination: "hzalo (Zalo Gateway)",
    action: "ALLOW",
    enforcement_point: "fw_hq, fw_telesale",
    enforcement_engine: "nftables",
    priority: 0,
    cookie: "n/a",
    enabled: true,
    configuration_status: "Enabled",
    lifecycle_status: "Applied",
    runtime_acknowledged: true,
    controller_acknowledged: true,
    updated_at: new Date().toISOString(),
  },
  {
    key: "allow_general_internet",
    name: "Truy cập Internet có kiểm soát (Firewall HA)",
    description: "Điều hướng lưu lượng Internet qua cụm Firewall HA lọc trạng thái stateful và SNAT.",
    source: "Internal Corporate LAN",
    destination: "WAN Internet",
    action: "ALLOW",
    enforcement_point: "fw_hq, fw_telesale",
    enforcement_engine: "nftables",
    priority: 0,
    cookie: "n/a",
    enabled: true,
    configuration_status: "Enabled",
    lifecycle_status: "Applied",
    runtime_acknowledged: true,
    controller_acknowledged: true,
    updated_at: new Date().toISOString(),
  },
  {
    key: "allow_guest_general_internet",
    name: "Cách ly Khách (Guest VLAN 120 Internet-Only)",
    description: "Khách vãng lai chỉ được cấp IP DHCP và đi thẳng ra Internet, chặn 100% vào mạng nội bộ.",
    source: "guest (VLAN 120)",
    destination: "hinternet (Chặn nội bộ)",
    action: "ALLOW",
    enforcement_point: "fw_hq",
    enforcement_engine: "nftables",
    priority: 0,
    cookie: "n/a",
    enabled: true,
    configuration_status: "Enabled",
    lifecycle_status: "Applied",
    runtime_acknowledged: true,
    controller_acknowledged: true,
    updated_at: new Date().toISOString(),
  },
  {
    key: "block_social_media",
    name: "Chặn mạng xã hội & Giải trí giờ hành chính",
    description: "Lọc gói tin HTTP/HTTPS domain blacklist ngăn chặn lãng phí băng thông và rủi ro an ninh.",
    source: "All Internal Users",
    destination: "hsocial (Social Media Services)",
    action: "DROP",
    enforcement_point: "fw_hq, fw_telesale",
    enforcement_engine: "nftables",
    priority: 0,
    cookie: "n/a",
    enabled: true,
    configuration_status: "Enabled",
    lifecycle_status: "Applied",
    runtime_acknowledged: true,
    controller_acknowledged: true,
    updated_at: new Date().toISOString(),
  },
  {
    key: "allow_it_support_controlled_access",
    name: "Đặc quyền Quản trị IT Support có kiểm soát",
    description: "Cho phép IT Support truy cập quản trị SSH (22), HTTPS (443), RDP (3389) tới các máy trạm và server.",
    source: "it_support",
    destination: "managed_users, server_farm",
    action: "ALLOW",
    enforcement_point: "core_hq, infra_access",
    enforcement_engine: "openflow",
    priority: 450,
    cookie: "0x1301",
    enabled: true,
    configuration_status: "Enabled",
    lifecycle_status: "Applied",
    runtime_acknowledged: true,
    controller_acknowledged: true,
    updated_at: new Date().toISOString(),
  },
];

export const mockPolicies: PolicyPayload = {
  policies: {
    isolate_hq_projects: true,
    allow_voice: true,
    voice_flow_priority: true,
    allow_zalo: true,
    allow_call_app: true,
    allow_general_internet: true,
    allow_guest_general_internet: true,
    block_social_media: true,
    allow_it_support_controlled_access: true,
    intersite_via_ipsec_l3: true,
    vlan93_l2vpn_primary_active: true,
    vlan93_l2vpn_backup_standby: true,
  },
  inventory: mockPolicyInventory.filter((policy) => ![
    "intersite_via_ipsec_l3",
    "vlan93_l2vpn_primary_active",
    "vlan93_l2vpn_backup_standby",
  ].includes(policy.key)),
  firewalls: mockFirewalls,
  phase44_runtime: {
    status: "verified",
    message_vi: "Phase 44 runtime acceptance verified on both sites (fw_hq & fw_telesale).",
    evidence_available: true,
  },
};

export const mockFlows: Array<Record<string, unknown>> = [
  { switch: "core_hq", table: "0", cookie: "0x1001", priority: 40000, match: "in_port=1,ip,nw_dst=10.250.10.10,tp_dst=5060", action: "ALLOW", packets: 14520, bytes: 1887600, duration: "3600s" },
  { switch: "core_hq", table: "20", cookie: "0x1002", priority: 45000, match: "ip,nw_proto=17,tp_dst=10000-20000", action: "ALLOW", packets: 89450, bytes: 17890000, duration: "3600s" },
  { switch: "core_hq", table: "30", cookie: "0x2001", priority: 30000, match: "dl_vlan=101,nw_dst=10.10.93.0/24", action: "DROP", packets: 412, bytes: 34608, duration: "3600s" },
  { switch: "core_hq", table: "30", cookie: "0x2001", priority: 30000, match: "dl_vlan=101,nw_dst=10.10.103.0/24", action: "DROP", packets: 285, bytes: 23940, duration: "3600s" },
  { switch: "core_hq", table: "30", cookie: "0x2001", priority: 30000, match: "dl_vlan=101,nw_dst=10.10.104.0/24", action: "DROP", packets: 198, bytes: 16632, duration: "3600s" },
  { switch: "core_hq", table: "10", cookie: "0x3001", priority: 35000, match: "dl_vlan=93,in_port=3", action: "ALLOW", packets: 52400, bytes: 8384000, duration: "3600s" },
  { switch: "core_hq", table: "30", cookie: "0x7001", priority: 32000, match: "nw_src=10.10.110.0/24,tp_dst=22,3389,443", action: "ALLOW", packets: 3210, bytes: 513600, duration: "3600s" },
  { switch: "core_hq", table: "0", cookie: "0x0", priority: 0, match: "priority=0", action: "ALLOW", packets: 245000, bytes: 49000000, duration: "3600s" },
  { switch: "access_floor1", table: "0", cookie: "0x1001", priority: 40000, match: "in_port=2,dl_vlan=101,ip,nw_dst=10.250.10.10", action: "ALLOW", packets: 8520, bytes: 1107600, duration: "3600s" },
  { switch: "access_floor1", table: "30", cookie: "0x5002", priority: 28000, match: "dl_vlan=120,nw_dst=10.10.0.0/16", action: "DROP", packets: 95, bytes: 7980, duration: "3600s" },
  { switch: "access_floor1", table: "0", cookie: "0x0", priority: 0, match: "priority=0", action: "ALLOW", packets: 189000, bytes: 37800000, duration: "3600s" },
  { switch: "access_floor2", table: "0", cookie: "0x2001", priority: 30000, match: "dl_vlan=103,nw_dst=10.10.104.0/24", action: "DROP", packets: 140, bytes: 11760, duration: "3600s" },
  { switch: "access_floor2", table: "0", cookie: "0x0", priority: 0, match: "priority=0", action: "ALLOW", packets: 142000, bytes: 28400000, duration: "3600s" },
  { switch: "ce_hq1", table: "0", cookie: "0x3001", priority: 35000, match: "in_port=1,dl_vlan=93", action: "ALLOW", packets: 68400, bytes: 10944000, duration: "3600s" },
  { switch: "ce_hq1", table: "0", cookie: "0x0", priority: 0, match: "priority=0", action: "ALLOW", packets: 75000, bytes: 12000000, duration: "3600s" },
  { switch: "ce_hq2", table: "0", cookie: "0x3002", priority: 34000, match: "in_port=1,dl_vlan=93", action: "ALLOW", packets: 340, bytes: 54400, duration: "3600s" },
  { switch: "ce_hq2", table: "0", cookie: "0x0", priority: 0, match: "priority=0", action: "ALLOW", packets: 1200, bytes: 192000, duration: "3600s" },
  { switch: "ce_branch1", table: "0", cookie: "0x3001", priority: 35000, match: "in_port=1,dl_vlan=93", action: "ALLOW", packets: 68150, bytes: 10904000, duration: "3600s" },
  { switch: "ce_branch1", table: "0", cookie: "0x0", priority: 0, match: "priority=0", action: "ALLOW", packets: 74500, bytes: 11920000, duration: "3600s" },
  { switch: "ce_branch2", table: "0", cookie: "0x3002", priority: 34000, match: "in_port=1,dl_vlan=93", action: "ALLOW", packets: 325, bytes: 52000, duration: "3600s" },
  { switch: "ce_branch2", table: "0", cookie: "0x0", priority: 0, match: "priority=0", action: "ALLOW", packets: 1150, bytes: 184000, duration: "3600s" },
  { switch: "dist_branch", table: "10", cookie: "0x3001", priority: 35000, match: "dl_vlan=93,in_port=2", action: "ALLOW", packets: 62100, bytes: 9936000, duration: "3600s" },
  { switch: "dist_branch", table: "0", cookie: "0x0", priority: 0, match: "priority=0", action: "ALLOW", packets: 95000, bytes: 15200000, duration: "3600s" },
  { switch: "access_branch", table: "0", cookie: "0x3001", priority: 35000, match: "in_port=1,dl_vlan=93", action: "ALLOW", packets: 58200, bytes: 9312000, duration: "3600s" },
  { switch: "access_branch", table: "30", cookie: "0x2001", priority: 30000, match: "dl_vlan=50,nw_dst=10.10.93.0/24", action: "DROP", packets: 82, bytes: 6888, duration: "3600s" },
  { switch: "access_branch", table: "0", cookie: "0x0", priority: 0, match: "priority=0", action: "ALLOW", packets: 82000, bytes: 13120000, duration: "3600s" },
  { switch: "infra_access", table: "0", cookie: "0x7001", priority: 32000, match: "nw_dst=10.10.100.10,tp_dst=67,68", action: "ALLOW", packets: 12400, bytes: 1984000, duration: "3600s" },
  { switch: "infra_access", table: "0", cookie: "0x0", priority: 0, match: "priority=0", action: "ALLOW", packets: 42000, bytes: 6720000, duration: "3600s" },
];
